// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabsbgyE7Mecz7Se2szr-CPliyyX5-Knw',
    appId: '1:167858986142:web:447c9655926a0c9911af8f',
    messagingSenderId: '167858986142',
    projectId: 'food-delivery-app-10194',
    authDomain: 'food-delivery-app-10194.firebaseapp.com',
    storageBucket: 'food-delivery-app-10194.appspot.com',
    measurementId: 'G-WLN7BZRFF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsyTZEqd1lPc6mS2j5hoRQTvpNnru9WDs',
    appId: '1:167858986142:android:6508c11c2495f8e011af8f',
    messagingSenderId: '167858986142',
    projectId: 'food-delivery-app-10194',
    storageBucket: 'food-delivery-app-10194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlSPDxbqSkS5oAAOskJMTuBZNcZqYTVkI',
    appId: '1:167858986142:ios:236f477f8ec3be6311af8f',
    messagingSenderId: '167858986142',
    projectId: 'food-delivery-app-10194',
    storageBucket: 'food-delivery-app-10194.appspot.com',
    androidClientId: '167858986142-qguo5800vhp598ea4c8l5cv2knvsgokm.apps.googleusercontent.com',
    iosClientId: '167858986142-ai7go0e4nsthv6kquhojkcdo3huact5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlSPDxbqSkS5oAAOskJMTuBZNcZqYTVkI',
    appId: '1:167858986142:ios:236f477f8ec3be6311af8f',
    messagingSenderId: '167858986142',
    projectId: 'food-delivery-app-10194',
    storageBucket: 'food-delivery-app-10194.appspot.com',
    androidClientId: '167858986142-qguo5800vhp598ea4c8l5cv2knvsgokm.apps.googleusercontent.com',
    iosClientId: '167858986142-ai7go0e4nsthv6kquhojkcdo3huact5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabsbgyE7Mecz7Se2szr-CPliyyX5-Knw',
    appId: '1:167858986142:web:66464ad9d357deb311af8f',
    messagingSenderId: '167858986142',
    projectId: 'food-delivery-app-10194',
    authDomain: 'food-delivery-app-10194.firebaseapp.com',
    storageBucket: 'food-delivery-app-10194.appspot.com',
    measurementId: 'G-43W2DSK6BG',
  );
}
